version: '3'
services:
  n8n:
    image: n8nio/n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_USER=username
      - N8N_BASIC_AUTH_PASSWORD=password
      - N8N_PORT=5678
      - NODE_ENV=production
      - DB_TYPE=mysql
      - DB_HOST=bossgrasser
      - DB_PORT=3306
      - DB_USER=username
      - DB_PASSWORD=password
      - DB_DATABASE=databasename
      - GENERIC_TYPE=fs
      - GENERIC_URL=/n8n-files/temp/app.js
